name: life
version: 0.0.1
author: Kyle Racette
description: A Life Simulation
homepage:
dependencies:
  browser: any
transformers:
- $dart2js:
    commandLineOptions: [--show-package-warnings]
    checked: true
    csp: true
    minify: false
    sourceMaps: true
    suppressHints: false
    suppressWarnings: false
    terse: true
    verbose: true